package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"projectcollection/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Dbtype)
// DB Table: Plural (dbtypes)
// Resource: Plural (Dbtypes)
// Path: Plural (/dbtypes)
// View Template Folder: Plural (/templates/dbtypes/)

// DbtypesResource is the resource for the Dbtype model
type DbtypesResource struct {
	buffalo.Resource
}

// List gets all Dbtypes. This function is mapped to the path
// GET /dbtypes
func (v DbtypesResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	dbtypes := &models.Dbtypes{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Dbtypes from the DB
	if err := q.All(dbtypes); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("dbtypes", dbtypes)
		return c.Render(http.StatusOK, r.HTML("dbtypes/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(dbtypes))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(dbtypes))
	}).Respond(c)
}

// Show gets the data for one Dbtype. This function is mapped to
// the path GET /dbtypes/{dbtype_id}
func (v DbtypesResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Dbtype
	dbtype := &models.Dbtype{}

	// To find the Dbtype the parameter dbtype_id is used.
	if err := tx.Find(dbtype, c.Param("dbtype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("dbtype", dbtype)

		return c.Render(http.StatusOK, r.HTML("dbtypes/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(dbtype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(dbtype))
	}).Respond(c)
}

// New renders the form for creating a new Dbtype.
// This function is mapped to the path GET /dbtypes/new
func (v DbtypesResource) New(c buffalo.Context) error {
	c.Set("dbtype", &models.Dbtype{})

	return c.Render(http.StatusOK, r.HTML("dbtypes/new.plush.html"))
}

// Create adds a Dbtype to the DB. This function is mapped to the
// path POST /dbtypes
func (v DbtypesResource) Create(c buffalo.Context) error {
	// Allocate an empty Dbtype
	dbtype := &models.Dbtype{}

	// Bind dbtype to the html form elements
	if err := c.Bind(dbtype); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(dbtype)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("dbtype", dbtype)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("dbtypes/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "dbtype.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/dbtypes/%v", dbtype.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(dbtype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(dbtype))
	}).Respond(c)
}

// Edit renders a edit form for a Dbtype. This function is
// mapped to the path GET /dbtypes/{dbtype_id}/edit
func (v DbtypesResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Dbtype
	dbtype := &models.Dbtype{}

	if err := tx.Find(dbtype, c.Param("dbtype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("dbtype", dbtype)
	return c.Render(http.StatusOK, r.HTML("dbtypes/edit.plush.html"))
}

// Update changes a Dbtype in the DB. This function is mapped to
// the path PUT /dbtypes/{dbtype_id}
func (v DbtypesResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Dbtype
	dbtype := &models.Dbtype{}

	if err := tx.Find(dbtype, c.Param("dbtype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Dbtype to the html form elements
	if err := c.Bind(dbtype); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(dbtype)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("dbtype", dbtype)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("dbtypes/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "dbtype.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/dbtypes/%v", dbtype.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(dbtype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(dbtype))
	}).Respond(c)
}

// Destroy deletes a Dbtype from the DB. This function is mapped
// to the path DELETE /dbtypes/{dbtype_id}
func (v DbtypesResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Dbtype
	dbtype := &models.Dbtype{}

	// To find the Dbtype the parameter dbtype_id is used.
	if err := tx.Find(dbtype, c.Param("dbtype_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(dbtype); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "dbtype.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/dbtypes")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(dbtype))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(dbtype))
	}).Respond(c)
}
