package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"projectcollection/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Host)
// DB Table: Plural (hosts)
// Resource: Plural (Hosts)
// Path: Plural (/hosts)
// View Template Folder: Plural (/templates/hosts/)

// HostsResource is the resource for the Host model
type HostsResource struct {
	buffalo.Resource
}

// List gets all Hosts. This function is mapped to the path
// GET /hosts
func (v HostsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	hosts := &models.Hosts{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Hosts from the DB
	if err := q.Eager().All(hosts); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("hosts", hosts)
		return c.Render(http.StatusOK, r.HTML("hosts/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(hosts))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(hosts))
	}).Respond(c)
}

// Show gets the data for one Host. This function is mapped to
// the path GET /hosts/{host_id}
func (v HostsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Host
	host := &models.Host{}

	// To find the Host the parameter host_id is used.
	if err := tx.Eager().Find(host, c.Param("host_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("host", host)

		return c.Render(http.StatusOK, r.HTML("hosts/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(host))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(host))
	}).Respond(c)
}

// New renders the form for creating a new Host.
// This function is mapped to the path GET /hosts/new
func (v HostsResource) New(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}
	c.Set("host", &models.Host{})
	environments := models.Environments{}
	tx.All(&environments)
	c.Set("environments", environments)

	return c.Render(http.StatusOK, r.HTML("hosts/new.plush.html"))
}

// Create adds a Host to the DB. This function is mapped to the
// path POST /hosts
func (v HostsResource) Create(c buffalo.Context) error {
	// Allocate an empty Host
	host := &models.Host{}

	// Bind host to the html form elements
	if err := c.Bind(host); err != nil {
		return err
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(host)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("host", host)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("hosts/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "host.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/hosts/%v", host.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(host))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(host))
	}).Respond(c)
}

// Edit renders a edit form for a Host. This function is
// mapped to the path GET /hosts/{host_id}/edit
func (v HostsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Host
	host := &models.Host{}

	if err := tx.Find(host, c.Param("host_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}
	environments := models.Environments{}
	tx.All(&environments)
	c.Set("environments", environments)

	c.Set("host", host)
	return c.Render(http.StatusOK, r.HTML("hosts/edit.plush.html"))
}

// Update changes a Host in the DB. This function is mapped to
// the path PUT /hosts/{host_id}
func (v HostsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Host
	host := &models.Host{}

	if err := tx.Find(host, c.Param("host_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Host to the html form elements
	if err := c.Bind(host); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(host)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("host", host)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("hosts/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "host.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/hosts/%v", host.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(host))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(host))
	}).Respond(c)
}

// Destroy deletes a Host from the DB. This function is mapped
// to the path DELETE /hosts/{host_id}
func (v HostsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Allocate an empty Host
	host := &models.Host{}

	// To find the Host the parameter host_id is used.
	if err := tx.Find(host, c.Param("host_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(host); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "host.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/hosts")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(host))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(host))
	}).Respond(c)
}
