package actions

import (
	"fmt"
	"net/http"

	"github.com/gobuffalo/buffalo"
	"github.com/gobuffalo/pop/v6"
	"github.com/gobuffalo/x/responder"

	"projectcollection/models"
)

// This file is generated by Buffalo. It offers a basic structure for
// adding, editing and deleting a page. If your model is more
// complex or you need more than the basic implementation you need to
// edit this file.

// Following naming logic is implemented in Buffalo:
// Model: Singular (Pool)
// DB Table: Plural (pools)
// Resource: Plural (Pools)
// Path: Plural (/pools)
// View Template Folder: Plural (/templates/pools/)

// PoolsResource is the resource for the Pool model
type PoolsResource struct {
	buffalo.Resource
}

// List gets all Pools. This function is mapped to the path
// GET /pools
func (v PoolsResource) List(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}
	// check the permissions of the user. If it hasn't got permission for the "pool.view" resource, return an error
	if !c.Value("current_user").(*models.User).HasPermissionFor("pool.view") {
		return c.Error(http.StatusUnauthorized, fmt.Errorf("You don't have permission to view pools"))
	}

	pools := &models.Pools{}

	// Paginate results. Params "page" and "per_page" control pagination.
	// Default values are "page=1" and "per_page=20".
	q := tx.PaginateFromParams(c.Params())

	// Retrieve all Pools from the DB
	if err := q.All(pools); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// Add the paginator to the context so it can be used in the template.
		c.Set("pagination", q.Paginator)

		c.Set("pools", pools)
		return c.Render(http.StatusOK, r.HTML("pools/index.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(pools))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(pools))
	}).Respond(c)
}

// Show gets the data for one Pool. This function is mapped to
// the path GET /pools/{pool_id}
func (v PoolsResource) Show(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}
	// check the permissions of the user. If it hasn't got permission for the "pool.view" resource, return an error
	if !c.Value("current_user").(*models.User).HasPermissionFor("pool.view") {
		return c.Error(http.StatusUnauthorized, fmt.Errorf("You don't have permission to view pools"))
	}

	// Allocate an empty Pool
	pool := &models.Pool{}

	// To find the Pool the parameter pool_id is used.
	if err := tx.Find(pool, c.Param("pool_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		c.Set("pool", pool)

		return c.Render(http.StatusOK, r.HTML("pools/show.plush.html"))
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(200, r.JSON(pool))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(200, r.XML(pool))
	}).Respond(c)
}

// New renders the form for creating a new Pool.
// This function is mapped to the path GET /pools/new
func (v PoolsResource) New(c buffalo.Context) error {
	// check the permissions of the user. If it hasn't got permission for the "pool.create" resource, return an error
	if !c.Value("current_user").(*models.User).HasPermissionFor("pool.create") {
		return c.Error(http.StatusUnauthorized, fmt.Errorf("You don't have permission to create pools"))
	}
	c.Set("pool", &models.Pool{})

	return c.Render(http.StatusOK, r.HTML("pools/new.plush.html"))
}

// Create adds a Pool to the DB. This function is mapped to the
// path POST /pools
func (v PoolsResource) Create(c buffalo.Context) error {
	// Allocate an empty Pool
	pool := &models.Pool{}

	// Bind pool to the html form elements
	if err := c.Bind(pool); err != nil {
		return err
	}
	// check the permissions of the user. If it hasn't got permission for the "pool.create" resource, return an error
	if !c.Value("current_user").(*models.User).HasPermissionFor("pool.create") {
		return c.Error(http.StatusUnauthorized, fmt.Errorf("You don't have permission to create pools"))
	}

	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}

	// Validate the data from the html form
	verrs, err := tx.ValidateAndCreate(pool)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the new.html template that the user can
			// correct the input.
			c.Set("pool", pool)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("pools/new.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "pool.created.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/pools/%v", pool.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.JSON(pool))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusCreated, r.XML(pool))
	}).Respond(c)
}

// Edit renders a edit form for a Pool. This function is
// mapped to the path GET /pools/{pool_id}/edit
func (v PoolsResource) Edit(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}
	// check the permissions of the user. If it hasn't got permission for the "pool.edit" resource, return an error
	if !c.Value("current_user").(*models.User).HasPermissionFor("pool.edit") {
		return c.Error(http.StatusUnauthorized, fmt.Errorf("You don't have permission to edit pools"))
	}

	// Allocate an empty Pool
	pool := &models.Pool{}

	if err := tx.Find(pool, c.Param("pool_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	c.Set("pool", pool)
	return c.Render(http.StatusOK, r.HTML("pools/edit.plush.html"))
}

// Update changes a Pool in the DB. This function is mapped to
// the path PUT /pools/{pool_id}
func (v PoolsResource) Update(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}
	// check the permissions of the user. If it hasn't got permission for the "pool.edit" resource, return an error
	if !c.Value("current_user").(*models.User).HasPermissionFor("pool.edit") {
		return c.Error(http.StatusUnauthorized, fmt.Errorf("You don't have permission to edit pools"))
	}

	// Allocate an empty Pool
	pool := &models.Pool{}

	if err := tx.Find(pool, c.Param("pool_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	// Bind Pool to the html form elements
	if err := c.Bind(pool); err != nil {
		return err
	}

	verrs, err := tx.ValidateAndUpdate(pool)
	if err != nil {
		return err
	}

	if verrs.HasAny() {
		return responder.Wants("html", func(c buffalo.Context) error {
			// Make the errors available inside the html template
			c.Set("errors", verrs)

			// Render again the edit.html template that the user can
			// correct the input.
			c.Set("pool", pool)

			return c.Render(http.StatusUnprocessableEntity, r.HTML("pools/edit.plush.html"))
		}).Wants("json", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.JSON(verrs))
		}).Wants("xml", func(c buffalo.Context) error {
			return c.Render(http.StatusUnprocessableEntity, r.XML(verrs))
		}).Respond(c)
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a success message
		c.Flash().Add("success", T.Translate(c, "pool.updated.success"))

		// and redirect to the show page
		return c.Redirect(http.StatusSeeOther, "/pools/%v", pool.ID)
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(pool))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(pool))
	}).Respond(c)
}

// Destroy deletes a Pool from the DB. This function is mapped
// to the path DELETE /pools/{pool_id}
func (v PoolsResource) Destroy(c buffalo.Context) error {
	// Get the DB connection from the context
	tx, ok := c.Value("tx").(*pop.Connection)
	if !ok {
		return fmt.Errorf("no transaction found")
	}
	// check the permissions of the user. If it hasn't got permission for the "pool.delete" resource, return an error
	if !c.Value("current_user").(*models.User).HasPermissionFor("pool.delete") {
		return c.Error(http.StatusUnauthorized, fmt.Errorf("You don't have permission to delete pools"))
	}

	// Allocate an empty Pool
	pool := &models.Pool{}

	// To find the Pool the parameter pool_id is used.
	if err := tx.Find(pool, c.Param("pool_id")); err != nil {
		return c.Error(http.StatusNotFound, err)
	}

	if err := tx.Destroy(pool); err != nil {
		return err
	}

	return responder.Wants("html", func(c buffalo.Context) error {
		// If there are no errors set a flash message
		c.Flash().Add("success", T.Translate(c, "pool.destroyed.success"))

		// Redirect to the index page
		return c.Redirect(http.StatusSeeOther, "/pools")
	}).Wants("json", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.JSON(pool))
	}).Wants("xml", func(c buffalo.Context) error {
		return c.Render(http.StatusOK, r.XML(pool))
	}).Respond(c)
}
